Repository hcsp/functional-comparator, pull requests merged in 2019-09, with the labels that each got.

#5 Comparator接口的实现
  src/main/java/com/github/hcsp/functional/Order.java
Labels: from:VIP, is:answer

#6 两种方法实现比较
  src/main/java/com/github/hcsp/functional/Order.java
Labels: is:answer

#7 assertEquals两个参数写反了，应该：第一个参数是expected，第二个是actual
  src/test/java/com/github/hcsp/functional/OrderTest.java
Labels: from:VIP, is:enhancement

#8 functional-comparator
  src/main/java/com/github/hcsp/functional/Order.java
Labels: from:VIP, is:answer
